apiVersion: v1
kind: PersistentVolume
metadata:
  name: ejercicio-pv
  namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/ejercicio-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ejercicio-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
