apiVersion: batch/v1
kind: Job
metadata:
  name: job-request-service
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: curl-container
        image: docker.io/library/curlimages/curl:latest
        command:
          - /bin/sh
          - -c
          - |
            echo "Haciendo petición a mi-servicio..."
            curl -v http://mi-servicio/ > /data/response.txt 2>&1
            echo "Respuesta guardada en /data/response.txt"
            cat /data/response.txt
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: ejercicio-pvc
      restartPolicy: Never
  backoffLimit: 1
